meta_product_name: "Somos Tu Puente"
meta_title: "Conectamos empresas con ONGs para lograr donaciones que tengan impacto social."
meta_description: "Relevant description"
meta_image: "logotransparente.png" # should exist in `app/assets/images/`

